# Generated by Django 4.2.7 on 2023-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(max_length=256, upload_to='savelink/images/', verbose_name='image')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название коллекции')),
                ('description', models.CharField(max_length=256, verbose_name='Описание коллекции')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'коллекция',
                'verbose_name_plural': 'коллекции',
            },
        ),
        migrations.CreateModel(
            name='UrlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип ссылки')),
            ],
            options={
                'verbose_name': 'Тип ссылки',
                'verbose_name_plural': 'Тип ссылок',
            },
        ),
    ]
